### ISSUE TITLE
Bug: random but frequent crashes

### ISSUE THREAD

**Issue by shotgunanaconda** [skymen/fmod#11]
I dont have detailed description since i cant replicate it. But FMOD seems to crash the game in what seems at random. I _think_ its when events of various sorts get triggered but i dont know for sure. Sometimes it closesthe window and sometimes it just crashes into a black screen. I havent added anything else that impacts the game on a system level so it seems to be fmod :/ 

This is reported from everyone that has tried, sadly this makes it unusable.

**Comment by skymen** [comment]
That sounds like a memory issue. I wonder if this can be mitigated or not since memory is a big limitation of the web at the moment.

**Comment by shotgunanaconda** [comment]
Jumping back in to say that it might not be all because of the fmod plugin, after removing im getting them way less frequently but still happening.

Do you have more information of the memory limits?

**Comment by skymen** [comment]
It really depends on your device and on your browser. There is no clear limit.

**Comment by shotgunanaconda** [comment]
@skymen i can now confirm crashes were not because of fmod but a bug with loadstates and hierarchies in c3. reported here https://github.com/Scirra/Construct-bugs/issues/8118. I will close this issue.
