### ISSUE TITLE
Bug: Playing events in quick succession (like a machine gun) is stuttery even at large (~150ms) intervals.

### ISSUE THREAD

**Issue by Tokinsom** [skymen/fmod#8]
This occurs in playback intervals of roughly 150ms or lower which is much higher than the recommended 16ms threshold for the default audio plugin.

Is [studioupdateperiod ](https://fmod.com/docs/2.01/api/studio-api-system.html#fmod_studio_advancedsettings )set to the default 20ms?

Contact for example.

**Comment by skymen** [comment]
I most likely had it set to the default.
Made a quick version to change this to 5ms, but I don't know if it's gonna work or if the issue is from something else.
https://github.com/skymen/fmod/releases/tag/1.0.0.2_1.0.0.4_0.0.0.0

Can you test this real quick so I know if I need to push this further and implemented properly

**Comment by skymen** [comment]
Plugin should no longer infinitely load in 1.0.0.4
https://github.com/skymen/fmod/releases/tag/1.0.0.4_1.0.0.4_0.0.0.0

**Comment by Tokinsom** [comment]
No longer infinitely loading but the stuttering issue persists.

**Comment by skymen** [comment]
https://github.com/skymen/fmod/pull/9

Apparently this PR by @AlexQ3D fixes this issue. Can you test again @Tokinsom

**Comment by Tokinsom** [comment]
@skymen Yes we tested this in my game and the FMOD Playground .c3p and it appears to be fixed. It's hard to say whether or not it affects playback quality but I haven't noticed anything unusual yet.

**Comment by Tokinsom** [comment]
Unfortunately it turns out reducing the buffer size does indeed affect the sound quality, but only on certain devices. With my external dac/amp which I originally tested on, everything was fine, but when routing audio through my mic's headphone/monitoring port the audio was very crackly.

I can't say this with 100% certainty without testing an earlier version with the original buffer size (they all get stuck on black screen) but this is likely to be the case.
